### ISSUE TITLE
Sorting order of version parts is inconsistent

### ISSUE THREAD

**Issue by jomo** [tj/n#263]
Here's what I get when using `n`:

```
  ο io/2.0.0
    io/1.1.0
    io/1.4.1
    io/1.4.2
    io/1.8.1
```

It looks like MAJOR is sorted descending, but MINOR and PATCH are sorted ascending. *([semver](http://semver.org/))*

**Comment by tedgaydos** [comment]
Good catch. Looks like the sort was not updated to account for the text (io and node) added to the display when io support was added. I will submit a PR.

**Comment by maxrimue** [comment]
Problem solved as of 1.4.0

**Comment by ma2ciek** [comment]
The problem still exists with versions >= x.10.x, because the versions are in the alphabetic order, not the number order, so the x.10.x version is just after the x.1.x version (for example 6.10.0)
